# Financial Viability {#sec-Finance}

## Source

The financial viability data used for the scorecards are not readily available from the data warehouse. **We receive this data on request, directly from the Treasury team.**

According to Trevor Brooks,

> "For now, the best way to get this information is to request the data from the Treasury leadership team (Trevor Brooks, Joseph Audino, and Michael Needham). The Business Office is currently developing our financial metrics in the PowerBI environment where it will become part of our monthly financial reporting process. Once the project moves to production, the metrics will be readily accessible following a monthly cadence."

## Days Cash on Hand {#sec-DaysCash}

Days Cash on Hand refers to the number of days that IDEA Texas could continue if all funding ceased using unrestricted dollars. Through the year, the Days Cash on Hand includes currently liquid assets. However, in June, IDEA updates this metric to include the value of all available lines of credit. The values provided for the scorecard refer to the June end of year snap shot, including the lines of credit.

## Debt Service Coverage Ratio {#sec-DebtRatio}

Debt Service Coverage Ratio estimates IDEA's ability to cover its total debt obligations with its current income. A ratio above 1 indicates that their is enough income to fully cover all debt.

## Percent of Per Pupil Revenue Going to Regional Office Budget {#sec-PerPupil}

At the time of writing, we have not been able to access the data necessary to estimate percent of per pupil revenue going to region office budgets. Conversations are ongoing with members of the finance team to determine how we may be able to add this metric in the future.
