# Teacher Supply {#sec-TeacherSupply}

## Percent of Teaching Positions Hired by First Day of Instruction {#sec-TeachHire}

At the time of this writing (September 2025), this metric is a bit in flux. Our desire is to have some measure of how many teaching positions were filled versus vacant at the beginning of the employment or school year, to assess difficulties in staffing teaching positions.

In Fall 2025, we relied on values provided in a slide deck report created by Limla Paul. The metric used was labeled as "% of Staffed Teachers & Co-Teachers as of 9/24/25" with the date the percentage refering to the first day of instruction within each region. She states that the values were computed as:

$$
\% \text{ Staffed} = \frac{\text{Headcount} + \text{Filled Vacancies}}{\text{Headcount} + \text{Filled Vacancies} + \text{Remaining Vacancies}}*100
$$

She also stated that in the future, Chris Thompson recommends instead using the calculation that is currently used in the staffing dashboard that Limla manages:

$$
\% \text{ Staffed} = \left(1 - \frac{\# \text{ of Remaining Vacancies}}{\text{Active Count} + \# \text{ of Remaining Vacancies}}\right)*100
$$

Where Remaining Vacancies refers to the remaining positions with open requisitions, and Active Count refers to current active staff who have begun work. This is the best proxy for percentage of staffed positions, but may miss any positions that have been hired (and therefore not have an active requisition), but where the staff member has not begun work.

### Source

In Fall 2025, the metric we used was from the from Slide 1 of the September [monthly staffing report](https://teams.microsoft.com/l/message/19:meeting_YjY1NDZkYTUtYTkwNi00ZTY4LWI5NWYtYmJlY2UxMDczNmFl@thread.v2/1757093022018?context=%7B%22contextType%22%3A%22chat%22%7D).

In the future, IDEA may be moving away from using Jobvite and into different applications for managing job requisitions. If, however, the current dashboard that pulls from Jobvite remains active, the recommended way to retrieve the desired data would be to follow the instructions below, keeping in mind the a few important notes:

-   To get Teacher positions on the **Instructional/Overall: % Staffed** page, be sure to unselect "Not Teacher Role" from the Teacher Label drop-down menu

-   Be careful using the date selection slider! Changing the dates changes what you are going to see in some sections of the dashboard, but not others.

Instructions

1.  Access the [Staffing Dashboard](https://app.powerbi.com/groups/me/reports/a5d80984-d4e3-411d-b301-900ac1c790ad/ac6eda202eb561291ee5?experience=power-bi)
2.  Navigate to the **Instructional/Overall: % Staffed** page
3.  **Leave the date slider as is!**
4.  Select desired region(s)
5.  Select desired teacher label(s). Options include:
    -   SpEd Teacher
    -   SpEd RISE Teacher
    -   SpEd Co-Teacher
    -   Not Teacher Role (UNSELECT THIS!)
    -   Flex Teacher
    -   Co-Teacher
6.  Scroll to %**Staffed by Week Start Date** table, and check the row you want.
    -   WeekStartDate is the Monday of the week.
7.  You can download the data by clicking the "..." button, selecting "Export Data," and exporting with "Data with current layout."

Note that we could select the week of school start for each region using its individual start date week or choose the same across regions. If we decide to choose the same date across regions, I *believe* we can receive the same percentage results by doing the following:

1.  Access the [Staffing Dashboard](https://app.powerbi.com/groups/me/reports/a5d80984-d4e3-411d-b301-900ac1c790ad/ac6eda202eb561291ee5?experience=power-bi)
2.  Navigate to the **Instructional/Overall: % Staffed** page
3.  Move the date slider end date to specific desired end date (I believe you can keep the start date as 7/1/2025 or move it without problems, as long as it is before the start of the week of our end date)
    -   For example, we may want 8/15 across all regions, move the end date to 8/15/2025
4.  Select *all* desired region(s)
5.  Select desired teacher label(s). Options include:
    -   SpEd Teacher
    -   SpEd RISE Teacher
    -   SpEd Co-Teacher
    -   Not Teacher Role (UNSELECT THIS!)
    -   Flex Teacher
    -   Co-Teacher
6.  Scroll to **Teachers & Co-Teachers: %Staffed by Region & Location** table, and see the percent staffed for each teacher type and a combination across teacher types selected.
    -   Note that RGV is split into subregions, so to get the full region, you would need to select only the 3 RGV regions and use the Total row.
    -   The title for the table remains "Teachers & Co-Teachers" regardless of what role type you select.
7.  You can download the data by clicking the "..." button, selecting "Export Data," and exporting with "Data with current layout."

### Notes & Exclusions

-   Note in Fall 2025, the data for the Rio Grande Valley region (RGV) was only available divided into its three sub-regions (Lower, Upper, and Middle). The percentage provided for the full RGV region is an average across the sub-regions. Although it is not a true (weighted) average, the averaged percentages cover a very small range from 98.43% to 99.52%, so we expect that the weighted average would not differ greatly from the recorded value.

## Year Over Year (YOY) Teacher Retention {#sec-YOYTeach}

Year Over Year (YOY) teacher retention is intended to represent the percentage of teaching staff hired in one school year that returned to a teaching position at IDEA Public Schools for the next school year. Each year, IDEA's Human Assets team develops a comprehensive specifications for calculating staff retention, as detailed in their Standard Operating Procedures (SOP), stored on [here](https://ideapublicschoolsorg.sharepoint.com/:u:/r/HumanAssets/SitePages/Retention-Policy.aspx?csf=1&web=1&e=6ODfpp) on The Hub.

To my understanding (Hilary Doe), most of these specifications are carried out when labeling each individual as a Leaver or not prior to the data being pushed to the Data Warehouse. For example, individuals who do not return because they retire are not counted as Leavers according to the SOP [@RetSOP2024]. Individuals with an Exit Reason of "Voluntary Retirement" are not listed as Leavers within the reporting.employees data. A full list of specifications, copied from the 2024-2025 Staff Retention SOP are listed in @sec-retEx.

### Source

The YOY teacher retention data come from the reporting.employees table in the data warehouse[@RetSOP2024] and are limited to staff in teaching positions (`filter(ISTEACHER == "1")`}).

```{r YOYret}
#| eval: false
#| include: true

reporting.employees <- get_table(.table_name = "Employees",
                                 .database_name = "Staffing",
                                 .schema = "Reporting", 
                                 .server_name = "RGVPDSD-DWPRD1") %>% 
  collect()

```

### Notes & Exclusions {#sec-retEx}

The following details are taken directly from the 2024-2025 Staff Retention Standard Operating Procedures [@RetSOP2024], however it is important to note that each year's SOP can be differ slightly, including the length of the staff retention year. For example, the 2023-2024 Staff Retention Year is defined as 7/1/2023 – 6/30/2024, whereas the 2024-2025 staff retention year is defined as 07/1/2024 – 08/14/2025 [@RetSOP2023; @RetSOP2024].

> Staff Retention Definitions
>
> -   The formula for calculating retention is as follows: $$\text{Retained} = \frac{1-\text{Leavers}}{\text{Headcount}}*100$$
> -   The 2024-25 Staff Retention Year is defined as 07/1/2024 – 08/14/2025 (specific employee categories may have a different start to their Staff Retention Year based on their work calendar, but will not be earlier than 07/01/2024 – details below).
> -   “Headcount” is defined as the sum of all full-time, permanent employees who worked at IDEA Public Schools between 07/1/2024 and 08/14/2025. Examples of staff job groups that fall into this category are Administrative Professionals, Campus Administrative Professionals, Clerical Technical, Instructional Support, Teachers, and Manual Trades.
>     -   Retention includes any staff member who is classified as full-time, permanent staff, including partial FTE staff. Descriptions of the employee classifications can be found in the Employee Handbook.
>     -   Chiefs are included in Executive Office retention, not the retention for their individual areas.
>     -   Principals-in-Residence count toward the retention of the school they are assigned to for their residency.
>     -   Founding Teacher Fellows count toward the retention of the school at which they are assigned for their fellowship.
>     -   All non-year-round staff who leave prior to the first day of their work calendar for the current staff retention year will be coded with an exit date prior to 08/15/2025 to ensure they do not count toward following staff retention year.
>     -   Exclusions: Employees classified as anything other than full-time, permanent employees are excluded from Headcount and Leavers. This includes, but is not limited to, the following titles:
>         -   Enrichment Instructor, Enrichment Specialist, 21st Century Enrichment Specialist
>         -   Intern, including Summer Interns and Year-round Interns
>         -   After School Care
>         -   Parent Liaison
>         -   Monitor, including Bus Monitor, Flex Monitor, Lunch Monitor, Recess Monitor, and School Monitor
>         -   Camp Rio Program Staff & Camp Counselor
>         -   FSS Substitute
>         -   Tutor
>         -   Athletic Coach
>         -   IDEA Substitute Teacher
>     -   “Leaver” is defined as the sum of all full-time, permanent employees who have an effective exit date between 07/1/2024 and 08/14/2025.
>         -   Full-time, permanent employees who transition into non-full-time permanent roles during the current Retention Year will count as leavers.
>         -   Full-time, permanent employees who retire will count as leavers.
>         -   The last full-time role an employee holds is the position held accountable for retention. If an employee changes during the year from full time role A to full time role B then leaves the organization, they will be counted as a leaver for role B.
>             -   Example: An API transitions to teacher in October and decides to leave at the end of the year. They will be counted as a teacher leaver
>         -   The last location an employee is based at and held a full-time role that they reported to is held accountable for retention of that employee. If an employee changes during the year from location A to location B, then leaves the organization, they will be counted as a leaver for location B as long as they reported to work at Location B.
>             -   Example: A teacher transfers from IDEA Pharr to IDEA Rise in December and then leaves at the end of the year. They will be counted as a teacher leaver for IDEA Rise.
>         -   Employees moving from a permanent, full-time position to another permanent, full-time position are not considered leavers.
>         -   Full-time employees in a permanent in the current retention year who transition to a non-full-time permanent role during the same retention year will count as a leaver.
>         -   Permanent, full-time and permanent, part-time employees who leave IDEA Public Schools and return to IDEA Public Schools in a permanent, full-time or permanent, part-time capacity during the same retention year will not count as leavers.
>         -   Employees leaving and returning to the organization in a retention-eligible role with a start date in the same school year (re-hire) do not count as leavers. Those employees who return to work after the start of the next retention year will count as leavers.
>         -   Positions that are eliminated due to budget constraints and/or grant-funded positions that are terminated because the grant concluded and was not continued will not count as leavers.
>         -   Employees who are reassigned but decline the reassignment and leave the organization will count as leavers attributed to the manager/campus for which they were employed on their last day of employment.
>         -   Positions that are eliminated for other reasons will count as leavers.
>         -   Employees coded with the following termination codes will not be counted as leavers:
>             -   IN04 - Death, IN05 - Ineligible For Hire, IN08 - Failed I-9 Verification, OT01 - Entity Change, OT02 - Employee did Not Start.
>             -   OT02 – Employee did Not Start will only apply to new hires who did not begin a position at IDEA, not transfers. o Staff in National roles will not be counted in regional staff retention. They will only count as headcount and leavers for their Chief Area team.
>         -   Staff members eligible to retire through their state employee retirement program and submit required paperwork within the staff retention year deadlines will not count as leavers once their official retirement is verified. o Leavers during the current staff retention year who are not exited before retention results for the current staff retention year are finalized, will count as leavers for the following staff retention year.
>         -   Leaver role, status, or location changes not entered within the current staff retention year that are not entered before retention results for current staff retention year are finalized will not be captured in the final staff retention report of the current staff retention year.
> -   “School” is defined as either Academy or College Prep, typically the unit led by a principal.
> -   “Campus” is defined as Academy + College Prep; typically, both schools at one location.
> -   The final retention metric will be rounded to the nearest whole number based on the tenths digit. (If .xx is ≥ .50, then it will round up. If .xx is \<.50, then it will round down.) For example:
>     -   84.50% will round to 85%
>     -   84.49% will round down to 84%
> -   Staff who are shared between Academy and College Prep will count 50% toward Academy, and 50% toward College Prep head count and leaver count. This includes all shared staff including, but not limited to, instructional staff, operations staff, and any school support staff. This ensures that shared staff, including operations, impact school retention. The formula is as follows: $$\text{School Retention} = 1-\frac{\text{School Leavers} + 0.5(\text{Shared Staff Leavers})}{\text{School Headcount} + 0.5(\text{Shared Staff Headcount})} $$
>
> All IDEA Public Schools Teacher Retention
>
> -   “Headcount” is defined as the sum of all full-time, permanent employees in the Teacher Job Group who work at IDEA Public Schools between the start of their 2024-25 Work Calendar and 08/14/2025.
>     -   Instructional staff (teachers and co-teachers/instructional support) and campus administrative professionals will count toward the school at which they work, not the campus.
>     -   Campus support staff (i.e. administrative assistants, testing coordinators, 21st century site coordinators) will count toward campus and school retention if they are shared and toward school retention if they are not shared.
> -   “Leaver” is defined as the sum of all full-time, permanent Teachers who have an effective exit date between the first day of their 24-25 School Year work calendar (even if they participate in summer school or summer professional development) and 08/14/2025.
>     -   All teachers who leave prior 08/15/2025 will be coded with an exit date prior to 08/15/2025 to ensure they do not count toward 2025-2026 retention.
>         -   Co-teachers and Founding Teacher Fellows do not count toward Teacher retention, to better align with PEIMS Teacher reporting, but do count toward All Staff retention. These roles will be included in the school All Staff retention but not in the school Teacher retention.
> -   The teacher retention year begins on the first day of their work calendar, not the first day of summer PD. If a returning teacher no-shows for the first days of all-staff BOY PD, even if s/he were part of summer PD, s/eh will be counted as a leaver for the previous school year.
>     -   If a New Hire is a no-show on the first day of their work calendar, they should be coded as OT02 – Employee did not start, which will exclude them from the count.o If an employee shows up for the first day of their work calendar and subsequently leaves, they will count toward retention that year.
>     -   Flex Teachers and Flex Co-Teachers count toward the retention for the Region in which they were hired, unless they have officially transitioned to a permanent campus-based teaching role.
> -   Flex Teachers and Flex Co-Teachers will not count toward the retention for the home campus at which they are based before they are assigned to a permanent campus-based role.

