# Enrollment Readiness / Student Demand {#sec-06Enroll}

Important to note the difference between enrollment goals and capacity!

## Percentage Meeting Enrollment Goal {#sec-06Goal}

Each year, each IDEA school has an assigned enrollment target or goal for each grade level they enroll, set by the Enrollment and School Launch Team. \[Add information about who sets these and how\].

For this metric, a unit (grade level, school, campus, or region) is considered to have met its enrollment goal if the total number of students enrolled on the First Day Of Persistence (FDOP) is at or above the total enrollment goal for that unit.

$${\% \text{ Meeting Enrollment Goal}} = \frac{\# \text{ of Students Enrolled at Unit at FDOP}}{\text{Total Enrollment Goal for Unit}}$$

If one school is under-enrolled but another is over-enrolled, a full campus may still meet its overall enrollment goal. For example, at FDOP 2025, enrollment at Austin Health Professions Academy was 13 students below its target (not meeting enrollment goal), but Austin Health Professions College Prep was 46 above its target (meeting enrollment goal). Therefore, the full Austin Health Professions campus was 33 students above its target and considered to be meeting its enrollment goal.

| Unit | Enrollment at FDOP | Target Enrollment | Meets Goal? |
|:--:|:--:|:--:|:--:|
| Health Professions Academy | 335 | 348 | No |
| Health Professions College Prep | 434 | 388 | Yes |
| **Health Professions Campus Total** | **769** | **736** | **Yes** |

: Example of Under- and Over-Enrollment at Individual Schools with a Campus Meeting Enrollment Goal

### Notes & Exclusions

-   Two IDEA schools enroll PreK

### Source

## Percentage Student Annual Persistence {#sec-06Persist}

### Notes & Exclusions

### Source

## Percentage of Schools/Campuses Under 85% Capacity (Model 1501) {#sec-06Cap}

### Notes & Exclusions

### Source

The STAAR data includes STAAR and high school level End-of-Course (EOC) assessments stored in IDEA's data warehouse[@STAAR].

```{r STAAR}
#| eval: false
#| include: true

STAAR <- get_table(.table_name = "STAAR", .database_name = "Dashboard",
                   .schema = "dbo", .server_name = "RGVPDRA-DASQL") %>%
  filter(
    ## Includes STAAR but not STAAR Alt 2 
      TestVersion == "S", 
    ## Includes Scored assessments only
      ScoreCode == "S", 
    ## Includes Math and English 
    (SubjectCode == "Math" |
     SubjectCode == "Reading" |
     SubjectCode == "Algebra I" |
     SubjectCode == "English I" |
     SubjectCode == "English II"),
    ## Select desired school years
    (SchoolYear == "2024-2025" |
     SchoolYear == "2023-2024")
  )
```
