project:
  type: book
  
book:
  title: "IDEA Growth Scorecard Documentation"
  author: "Hilary Doe"
  date: "9/11/2025"
  cover-image: TitlePage.png
  chapters:
    - index.qmd
    - 01-SchoolPerformance.qmd
    - 02-FinancialViability.qmd
    - 03-CapitalCapacity.qmd
    - 04-TeacherSupply.qmd
    - 05-Leadership.qmd
    - 06-Enrollment.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex

editor: visual

